#ifndef IVISOR_THERMO_COMMON_H_
#define IVISOR_THERMO_COMMON_H_

#define MLX_CTRL_SUBPAGES_MODE_OFFS (0)
#define MLX_CTRL_SUBPAGES_MODE_MASK (1 << MLX_CTRL_SUBPAGES_MODE_OFFS)
#define MLX_CTRL_SUBPAGES_MODE_OFF (0 << MLX_CTRL_SUBPAGES_MODE_OFFS)
#define MLX_CTRL_SUBPAGES_MODE_ON  (1 << MLX_CTRL_SUBPAGES_MODE_OFFS)

#define MLX_CTRL_OVERWRITE_OFFS (2)
#define MLX_CTRL_OVERWRITE_MASK (1 << MLX_CTRL_OVERWRITE_OFFS)
// hold data ON
#define MLX_CTRL_OVERWRITE_OFF (1 << MLX_CTRL_OVERWRITE_OFFS)
// hold data OFF
#define MLX_CTRL_OVERWRITE_ON  (0 << MLX_CTRL_OVERWRITE_OFFS)

#define MLX_CTRL_AUTO_TOOGLE_OFFS (3)
#define MLX_CTRL_AUTO_TOOGLE_MASK (1 << MLX_CTRL_AUTO_TOOGLE_OFFS)
// select by user ON
#define MLX_CTRL_AUTO_TOOGLE_OFF (1 << MLX_CTRL_AUTO_TOOGLE_OFFS)
// select by user OFF
#define MLX_CTRL_AUTO_TOOGLE_ON  (0 << MLX_CTRL_AUTO_TOOGLE_OFFS)

#define MLX_CTRL_SUBPAGE_IDX_OFFS (4)
#define MLX_CTRL_SUBPAGE_IDX_MASK (7 << MLX_CTRL_SUBPAGE_IDX_OFFS)

#define MLX_CTRL_REFRESH_RATE_OFFS (7)
#define MLX_CTRL_REFRESH_RATE_MASK (7 << MLX_CTRL_REFRESH_RATE_OFFS)

#define MLX_CTRL_RESOLUTION_ADC_OFFS (10)
#define MLX_CTRL_RESOLUTION_ADC_MASK (3 << MLX_CTRL_RESOLUTION_ADC_OFFS)

#define MLX_CTRL_MODE_OFFS        (12)
#define MLX_CTRL_MODE_MASK        (1 << MLX_CTRL_MODE_OFFS)
#define MLX_CTRL_MODE_INTERLEAVED (0 << MLX_CTRL_MODE_OFFS)
#define MLX_CTRL_MODE_CHESS       (1 << MLX_CTRL_MODE_OFFS)


typedef enum MLX_FREQ {
	MLX_FREQ_0_5 = 0,
	MLX_FREQ_MIN = MLX_FREQ_0_5,
	MLX_FREQ_1 = 1,
	MLX_FREQ_2 = 2,
	MLX_FREQ_4 = 3,
	MLX_FREQ_8 = 4,
	MLX_FREQ_16 = 5,
	MLX_FREQ_32 = 6,
	MLX_FREQ_64 = 7,
	MLX_FREQ_MAX = MLX_FREQ_64,
} mlx_freq_t;

typedef enum MLX_RESOLUTION {
	MLX_RESOLUTION_16_BIT = 0,
	MLX_RESOLUTION_MIN = MLX_RESOLUTION_16_BIT,
	MLX_RESOLUTION_17_BIT = 1,
	MLX_RESOLUTION_18_BIT = 2,
	MLX_RESOLUTION_19_BIT = 3,
	MLX_RESOLUTION_MAX = MLX_RESOLUTION_19_BIT,
} mlx_resolution_t;

#define MLX_MATR_WIDTH (32)
#define MLX_MATR_HEIGHT (24)
#define MLX_MATR_PIXEL_COUNT (MLX_MATR_WIDTH*MLX_MATR_HEIGHT)

#define MLX_TEMP_MIN (-40)
#define MLX_TEMP_MAX (300)

#define CELCIUS_TO_FAHRENHEIT(val) ((val) * 9.0f / 5.0f + 32.0f)
#define FAHRENHEIT_TO_CELCIUS(val) (((val) - 32.0f) * 5.0f / 9.0f)

#endif
